### ISSUE TITLE
Implement validate function and unit tests

### ISSUE THREAD

**Issue by jamesaoverton** [IEDB/tetramer-validator#1]
The first thing we need is a `validate` function that takes four fields from the mockup and returns None on success and a string with an error message on failure. Each of the fields will have to be validated individually, then there will have to be validation between the fields. When any step of the validation fails, that function should return a useful error message explaining the problem (validation should stop there). The four fields are:

Peptide Sequence | Modification Type | Modification Position | MHC Name |  note
---|---|---|---|---
NLVPMVATV | oxidation | M5 | HLA-A*02:01 | valid
NLVPOVATV | oxidation | M5 | HLA-A*02:01 | invalid combination of sequence and modification

We also need unit tests covering  a wide range of valid and invalid inputs. A developer should be able to `git clone` the repository, run `pytest`, and see the test results.

**Comment by apmody** [comment]
Apurva Mody is inviting you to a scheduled Zoom meeting.

Topic: Zoom Meeting
Time: Aug 18, 2020 11:47 AM Pacific Time (US and Canada)

Join Zoom Meeting
https://zoom.us/j/92305423072?pwd=bnUvOUNBalhSYjJ5bm96K2NOSnp3QT09

Meeting ID: 923 0542 3072
Passcode: fRWSrl5S54

**Comment by jamesaoverton** [comment]
1. We'll need a list of the valid Modification Types and their codes for the Modification Position from @rvita
2. We'll take the MHC name from MRO's [molecules.tsv](https://github.com/IEDB/MRO/blob/master/ontology/molecule.tsv): first filter for "complete molecule" or "partial molecule", then use the name in the second column (IEDB Label)
