### ISSUE TITLE
Typeahead for MHC name

### ISSUE THREAD

**Issue by apmody** [IEDB/tetramer-validator#22]
Will need to use Bloodhound for Typeahead implementation of MHC name field on webserver.

@rvita sent me "class II multimers.xlsx" sometime ago which has example data for mapping of sequences to MHC names.  Are there going to be more names?  Because there will be a need for the data when implementation of Typeahead does happen for MHC name (related to issue https://github.com/IEDB/tetramer-validator/issues/21)

**Comment by rvita** [comment]
Apurva, I do not understand what "mapping of sequences to MHC names" means. class II multimers.xlsx is one set of example data from the NIH tetramer facility & it contains example peptide sequences and example MHC terms. This sheet contained only the class II tetramers = all MHC terms in this set are class II MHC. The other sheet from the NIH contains additional examples from the NIH tetramer facility (2020-09-01 _tetramer_RV.xlsx) & it contains example peptide sequences and example MHC terms where some of the peptides have modifications. Those are the only two example sets of data that we have from the NIH tetramer facility. Each peptide sequence must be validated independent of the MHC term. Linear peptides are validated to ensure that they contain only valid amino acid letters or the letter X. Separately, all MHC terms are validated to MRO. Any linear peptide can be combined with any MHC term & each is validated separately.
