### ISSUE TITLE
Improvements to CLI

### ISSUE THREAD

**Issue by jamesaoverton** [IEDB/tetramer-validator#23]
1. I think the program should look for columns with certain names, not certain positions.
2. Since the input file is required, I think it should be a positional argument: `tv foo.tsv`.
3. By default the output should go to STDOUT.
4. The three "Parsing * file" messages are not very informative, and should be omitted.
5. When the program can't read the input file, it's an error, so the program should exit with a non-zero exit code: `sys.exit(1)` not `quit()`
6. The final `print(f"Please see {filename} for any errors")` is not informative and should be omitted: the user has either specified a file name or they see the results in STDOUT.
7. If any validation errors are found, the program should `sys.exit(1)`

**Comment by apmody** [comment]
For item 7, what about the situation where only one row out of many is incorrect?

**Comment by jamesaoverton** [comment]
When there's any invalid data, we should print a message and exit 1.

**Comment by apmody** [comment]
Should also add optional argument for when there is no MHC name
