### ISSUE TITLE
Improvements discussed at 9/24/2020 call

### ISSUE THREAD

**Issue by apmody** [IEDB/tetramer-validator#30]
1. Make "MHC name" read as "MHC molecule" on Web form
2. Move "MHC molecule" field to be the first in the Web form.  
3. Peptide sequence and MHC are required in Web form.  Throw errors if they are not there.
4. Keep MHC mandatory in main `validate` function in [validate.py](https://github.com/IEDB/tetramer-validator/blob/master/tetramer_validator/validate.py), but have separate function to validate the modification type with peptide sequence and modification position.  Such function would call `validate_mod_pos`, but then it would have the code to verify 
	1. Only amino acids or X are contained in peptide sequence
	2. Number of modification positions matches the number of modification types
	3. The modification types are from PTM list.

**Comment by jamesaoverton** [comment]
For 4, my suggestion would be to pull out a `validate_peptide` function that takes three arguments: peptide sequence and optional modification names and positions. Then the main `validate` function should take four arguments, now including the MHC molecule, and call `validate_peptide`. This should cover all our use cases without duplicating any code.

We have a general goal to return errors as dictionaries, which will help with a few of the items below.

Other notes from the call:

- modification name suggestions should include synonyms -- need to discuss the details
- when running this code on IEDB data, we may want a preprocessing step that replaces the modification names with our preferred names

From Bjoern's email:

- add examples to input fields using the `placeholder` attribute
- use a "?" icon to link to documentation
- revise error messages to be maximally helpful to users -- we'll implement this along with structured errors

Other suggestions:

- add a Reset button
- add a few examples with links that fill the form
- with the structured errors we can make use of Bootstrap's [server-side form validation](https://getbootstrap.com/docs/4.5/components/forms/#server-side) to highlight the valid and invalid fields

**Comment by apmody** [comment]
>   - with the structured errors we can make use of Bootstrap's [server-side form validation](https://getbootstrap.com/docs/4.5/components/forms/#server-side) to highlight the valid and invalid fields

Are we covering the case when there are two (or more) incorrect fields and we highlight each of them?  For example, if there is an invalid amino acid entered and the modification positions are in the wrong format (e.g. 10F instead of F10).

**Comment by jamesaoverton** [comment]
The `validate` function could return a list of errors, if we make some other changes. There's a bit of a complexity cost, but I think that would be better.
