### ISSUE TITLE
Accumulate and export a list of tetramers

### ISSUE THREAD

**Issue by jamesaoverton** [IEDB/tetramer-validator#40]
As the user enters valid tetramers into the web interface, it should accumulate a list. Then it should offer an option to export them in a table (CSV and Excel).

**Comment by apmody** [comment]
Should this be something like where they can press a button and another row appears?  Or can we use cookies?

**Comment by jamesaoverton** [comment]
Good questions. I'm leaning toward multiple rows. Maybe the query strings could include numbers for rows after the first. Example with two rows: https://tetramers.ontodev.com/?mhc_name=H2-Db&pep_seq=HA&mhc_name_2=H2-Dd&pep_seq_2=HAHA

MHC Name | Peptide Sequence
---|---
H2-Db | HA
H2-Dd | HAHA

Or maybe once there's multiple rows then it's better to switch to POST with CSV. (I do still like allowing GET and query params for the single case.)
