### ISSUE TITLE
Validate tables

### ISSUE THREAD

**Issue by jamesaoverton** [IEDB/tetramer-validator#8]
We should be able to run the validator on tables. The input should be a CSV, TSV, or Excel file. The output should be a TSV file indicating the location of the problem and its description, using the [standard problem table](https://github.com/ontodev/cogs#standardized-problems-tables) format that we're using for other tools.

For reading Excel, I prefer [OpenPyXL](https://openpyxl.readthedocs.io/en/stable/).

**Comment by apmody** [comment]
For Excel file, should we have rules for how someone should format the queries before they go through validator?

**Comment by jamesaoverton** [comment]
I would just expect the table to have columns with specific names, put the rows in a dictionary (like you're doing), then for each row call the `validate` function with arguments from the dictionary. For Excel I would just read the first sheet, or maybe the active sheet, although maybe we could accept the sheet name as an argument.

**Comment by apmody** [comment]
Should we also have ability to upload file on web page?

**Comment by jamesaoverton** [comment]
That would be a nice feature to have, but it's not a top priority.
