### ISSUE TITLE
Implement command-line interface

### ISSUE THREAD

**Issue by jamesaoverton** [IEDB/tetramer-validator#9]
Building on #8, we should be able to validate a table from the command-line. Please use the `argparse` library. Here's a simple template: https://github.com/knocean/practises/blob/master/python/cli.py

**Comment by apmody** [comment]
Do we want to parse command line args for peptide sequence, modification name, modification type, and MHC name?

**Comment by jamesaoverton** [comment]
Those should be the columns in the spreadsheet. The only command line argument we need is the input file, and maybe the output file.
